// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrtn0JsisWRWzmD-uutWBOs96DbhIorks',
    appId: '1:595082308204:web:917090f360e0e757740649',
    messagingSenderId: '595082308204',
    projectId: 'notification-1-18a84',
    authDomain: 'notification-1-18a84.firebaseapp.com',
    storageBucket: 'notification-1-18a84.firebasestorage.app',
    measurementId: 'G-VCFJBZJPH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC6W532tWjWcKksB6qzo-V2vO0ruKtNwU',
    appId: '1:595082308204:android:d699e26d397b1ab5740649',
    messagingSenderId: '595082308204',
    projectId: 'notification-1-18a84',
    storageBucket: 'notification-1-18a84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCsZ1F-a7MJmz07oKOp8WdwYdkRBxUJxI',
    appId: '1:595082308204:ios:6bfd498dda7681bd740649',
    messagingSenderId: '595082308204',
    projectId: 'notification-1-18a84',
    storageBucket: 'notification-1-18a84.firebasestorage.app',
    iosBundleId: 'com.example.skolyozmobil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCsZ1F-a7MJmz07oKOp8WdwYdkRBxUJxI',
    appId: '1:595082308204:ios:6bfd498dda7681bd740649',
    messagingSenderId: '595082308204',
    projectId: 'notification-1-18a84',
    storageBucket: 'notification-1-18a84.firebasestorage.app',
    iosBundleId: 'com.example.skolyozmobil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrtn0JsisWRWzmD-uutWBOs96DbhIorks',
    appId: '1:595082308204:web:cc7e8d61d61e133f740649',
    messagingSenderId: '595082308204',
    projectId: 'notification-1-18a84',
    authDomain: 'notification-1-18a84.firebaseapp.com',
    storageBucket: 'notification-1-18a84.firebasestorage.app',
    measurementId: 'G-Y7P1LRK6LF',
  );
}
